// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.myblog.transfer;

import com.myblog.transfer.Timer;

privileged aspect Timer_Roo_JavaBean {
    
    public String Timer.getUsername() {
        return this.username;
    }
    
    public void Timer.setUsername(String username) {
        this.username = username;
    }
    
}
